### ISSUE TITLE
For Sale doesn't link to button url

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/Art-Store#10]

**Comment by jazzsequence** [comment]
when URL is set as payment method

**Comment by jazzsequence** [comment]
please comment back if this was tested and working

**Comment by safranck** [comment]
OK testing now and will update all

**Comment by safranck** [comment]
Tested, not able to get button to display in new version.

**Comment by jazzsequence** [comment]
User error, see #22 
http://wpartstore.com/work/charles-bukowski-by-dave-mcdowell/

**Comment by safranck** [comment]
Widgets and content area meta information now working and links to correct url. Thank you!
