### ISSUE TITLE
related products widget shows current product

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/Art-Store#11]
need to exclude current item

**Comment by jazzsequence** [comment]
This should be fixed with 909c54a58ff1f6abcf382d96f7395ab431b27112

please test and confirm

**Comment by safranck** [comment]
Unable to view related items widget

**Comment by jazzsequence** [comment]
Widget was never added to widget area. see #22 
http://wpartstore.com/work/charles-bukowski-by-dave-mcdowell/

**Comment by safranck** [comment]
Tested, did not see current item in related item list. Good job!
