### ISSUE TITLE
related products widget does not show related product

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/Art-Store#12]
related to #11

**Comment by jazzsequence** [comment]
this seems to actually be working now that i have some data...related products are displaying. can you confirm?

**Comment by jazzsequence** [comment]
please comment back if this was tested and working

**Comment by safranck** [comment]
Related products widget is not appearing

**Comment by jazzsequence** [comment]
Related products widget was never added to widget area. See #22 
http://wpartstore.com/work/charles-bukowski-by-dave-mcdowell/

**Comment by safranck** [comment]
Related items are shown in the widget or content area. Appears to be working swell. Thank you!
