### ISSUE TITLE
gallery javascript isn't loading on gallery page

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/Art-Store#13]

**Comment by jazzsequence** [comment]
Looks like the issue is here...maybe using a .min.js file that's not linked correctly?

![image](https://cloud.githubusercontent.com/assets/991511/7544904/afc5a8d6-f58e-11e4-8901-cb837d8fdb02.png)

**Comment by safranck** [comment]
Confirmed, here is a live exmaple with data: http://wpartstore.com/gallery/

**Comment by jazzsequence** [comment]
this should be fixed with 536ee436250644f54d374241d79d52d1e3db4c48

**Comment by jazzsequence** [comment]
please comment back if this was tested and working

**Comment by safranck** [comment]
The scrolling gallery displays now but acts wonky with Mac trackpad in Chrome

**Comment by jazzsequence** [comment]
scroll will be addressed in #21
