### ISSUE TITLE
empty price displays when no price is set

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/Art-Store#16]

**Comment by jazzsequence** [comment]
should be fixed with 93e5a96305b6110e5df021daa9409fe72ffbc059

**Comment by jazzsequence** [comment]
please comment back if this was tested and working

**Comment by safranck** [comment]
unable to test, widget/content meta information is not displaying

**Comment by jazzsequence** [comment]
User error, see #22 
http://wpartstore.com/work/charles-bukowski-by-dave-mcdowell/

**Comment by safranck** [comment]
Perfect, no price title is displayed when left empty. Looks good.
