### ISSUE TITLE
URL to button image showing instead of button image

### ISSUE THREAD

**Issue by safranck** [jazzsequence/Art-Store#17]
![buttonlink showing](https://cloud.githubusercontent.com/assets/3579430/7546122/86682cd8-f58f-11e4-8130-ea82009dc8ed.png)
![button image not displaying](https://cloud.githubusercontent.com/assets/3579430/7546124/8f358306-f58f-11e4-9c7f-806a4c9a31d0.png)

**Comment by jazzsequence** [comment]
this should be fixed now

**Comment by jazzsequence** [comment]
please comment back if this was tested and working
