### ISSUE TITLE
Plugin banner

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/Art-Store#19]
Need logo and banner for WP repo: https://wordpress.org/plugins/about/faq/#banners

**Comment by safranck** [comment]
![banner-772x250](https://cloud.githubusercontent.com/assets/3579430/7595462/1704bcac-f89c-11e4-97ae-402b8c0ffda0.png)
![icon-256x256](https://cloud.githubusercontent.com/assets/3579430/7595470/1e5fbd9e-f89c-11e4-87a9-e03f970ac053.png)
![icon-128x128](https://cloud.githubusercontent.com/assets/3579430/7595471/2272ea46-f89c-11e4-88a3-aaa40fafe558.png)
