### ISSUE TITLE
disable mousewheel scroll

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/Art-Store#21]
improves the scrolling ux

**Comment by jazzsequence** [comment]
fixed in e73a17d59938e99578857ed342533d91e2886077

disabled mousewheelscroll. can still scroll by hovering over the edges and by clicking/touching the ends of the gallery.

**Comment by jazzsequence** [comment]
please test and let me know if scrolling behavior is improved.

**Comment by safranck** [comment]
Yes! Much better thank you!!! Tested and works much better.
