### ISSUE TITLE
edit banner image

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/Art-Store#24]
logo/icon gets covered by the plugin name on the WordPress.org repo. adjust banner image to make the icon smaller and sit on top of the plugin name instead of being obscured by it

![wordpress_ _wp_art_store_ _wordpress_plugins](https://cloud.githubusercontent.com/assets/991511/7917811/3c1450a8-084a-11e5-89ed-391cc39875f6.png)

**Comment by safranck** [comment]
pushed up  to develop branch but here is the revised copy just in case
![banner-772x250](https://cloud.githubusercontent.com/assets/3579430/7926707/0d4b846c-088b-11e5-82ed-a3c515b2a31e.png)
