### ISSUE TITLE
Add Options page

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/Art-Store#3]
if possible, we shouldn't load all the js on every single page. if nothing else, options page should have an option to define what page our scroll is going to be on.

there will be some product stuff here, too

**Comment by jazzsequence** [comment]
Other options:
- button image
- enquire for price (if button html is left blank)
- html code or url (allow users to use PayPal Button URL)

**Comment by safranck** [comment]
Need a field for dimensions width: _____  height:_____ depth:_____
This should show if the Art Form is painting, sketch, mixed media, sculpture
WIdth + Height should be required and depth can be null

**Comment by jazzsequence** [comment]
Maybe we can add width/height/depth and just not make them required...my concern is that if they add a new art form, they'll have no way of being able to add dimensions to their new art forms

**Comment by jazzsequence** [comment]
created a new ticket for dimensions #6
