### ISSUE TITLE
Add Widgets

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/Art-Store#4]
Widgets will be ported/adapted from https://github.com/jazzsequence/Products

**Comment by safranck** [comment]
Sounds awesome! What are the widgets?

**Comment by jazzsequence** [comment]
This is the file in the products plugin that has all the widgets:  https://github.com/jazzsequence/Products/blob/master/inc/widgets.php

One has all the product meta (price, pay now button, other info), one was a cross-sales widget where you could explicitly feature another product that you wanted to relate to the one that the user was looking at (I'll probably leave that one out), one went with a testimonials post type (which I'm also leaving out), and then there's a related products widget that shows items that are related to the one you're currently looking at (based on taxonomies). since we have a couple different taxonomies in this plugin, I'll probably end up rebuilding that one for the most part.

**Comment by jazzsequence** [comment]
product information widget is good to go

![image](https://cloud.githubusercontent.com/assets/991511/6785804/9242ee8c-d14d-11e4-93c2-317acf38f52f.png)

next up, related products widget

**Comment by jazzsequence** [comment]
Set to needs-testing -- don't currently have enough products to test the related products widget. pushed to develop branch.

**Comment by safranck** [comment]
Related products widget shows up on all pages, should it only show up on gallery pages?

**Comment by jazzsequence** [comment]
nope, but that's covered in #15
