### ISSUE TITLE
shortcode to display the scrolling gallery

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/Art-Store#5]

**Comment by jazzsequence** [comment]
shortcode is added. should be working but needs testing. 

**Usage:**

To just display the gallery with the default settings use:

`[art-store-gallery]`

To customize the height _and_ the width use:

`[art-store-gallery height=500 width=250]`

To customize the height _or_ the width (the result will be square) use:

`[art-store-gallery height=500]`
`[art-store-gallery width=500]`

**Comment by safranck** [comment]
Thanks, I have this week mostly free so I will be focusing on getting this tested and anything else updated/documented. Thank you so much for your help!

**Comment by safranck** [comment]
http://wpartstore.com/gallery/ except when the number of items exceeds the width, perhaps related to javascript not loading issue

**Comment by jazzsequence** [comment]
yep, that's the js issue in #13
